"""add_summary_json_to_insights

Revision ID: 77bec728a8fe
Revises: e17535ae30af
Create Date: 2026-06-25 08:53:01.294604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77bec728a8fe'
down_revision: Union[str, None] = 'e17535ae30af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('summary_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'summary_json')
    # ### end Alembic commands ###
