"""Add new columns to user and insight

Revision ID: e17535ae30af
Revises: 941dc63122b6
Create Date: 2026-06-24 11:21:48.272431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17535ae30af'
down_revision: Union[str, None] = '941dc63122b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('insights', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'insights', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('team', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('retention_days', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'retention_days')
    op.drop_column('users', 'team')
    op.drop_constraint(None, 'insights', type_='foreignkey')  # type: ignore[arg-type]
    op.drop_column('insights', 'tokens_used')
    op.drop_column('insights', 'user_id')
    # ### end Alembic commands ###
